### ISSUE TITLE
after upgrade to meteor 1.0.5 and promise 2.0.1 there's no return value from .then(myFunc())

### ISSUE THREAD

**Issue by tintoverano** [chicagogrooves/deanius-meteor-promise#2]
hi,

after the upgrade there's no return value from the promise function: .then(myFunc())

````
...
      Meteor.promise ("...", ...)
        .then (myFunc ())
        .done (function () {..})
        .fail (function (err) {console.error ("Bad", err);})
...

function myFunc (myParam) {
       myParam comes as undefined
       ...
}
````

myParam is 'undefined' whereas the promise method should return it

I can see that the method is called and there's the value which is to be received back, this worked before nicely

it worked before the upgrade, I couldn't figure out based on the release notes what was the change which resulted in my issue

what do you think what do problem could be?

thanks a lot

**Comment by chicagogrooves** [comment]
Thanks for the illustration of the code. In your example, the parens after myFunc should be omitted
```
      Meteor.promise ("...", ...)
        .then (myFunc) // <- look, no parens
```

I added an example to the test suite [here](https://github.com/chicagogrooves/deanius-meteor-promise/blob/master/tests/identity-tests.js#L30)..

Does that solve it for you ?

**Comment by tintoverano** [comment]
yesss!! works like a charm
thanks for the support
