### ISSUE TITLE
Am I doing this right?

### ISSUE THREAD

**Issue by tehfailsafe** [chicagogrooves/deanius-meteor-promise#3]
Looks like I'm not sure how to follow your example, I get errors like `TypeError: Object #<Promise> has no method 'done'` and `[TypeError: Object #<Object> has no method 'then']` while trying to arrange things properly.

Following along the meteor chef example for Stripe integration, here's my failing code:
```
Meteor.methods({
  createSubscription: function(customer) {
    var user = Meteor.users.findOne({_id: customer.userId});

    var getCustomer = function(customer){
      return Meteor.promise("stripeCreateCustomer", customer);
    };

    var getSubscription = function(stripeCustomer){
      return Meteor.promise("stripeCreateSubscription", stripeCustomer.id, customer.plan)
    };


    Meteor.promise("getCustomer")
          .then(getSubscription)
          .catch(function(err){
            console.log(err);
          })
          .done(function(customer){
            console.log("promise complete ", customer);
          })
  }
});
```

Could you give some advice? Am I supposed to put the promises in the client view template instead?

**Comment by chicagogrooves** [comment]
It looks like you got upgraded to version `2.0`, which eliminates `done` in the interest of being compatible with ES6 promises. You can:

1. replace `done` with `then` or..
1. depend on `deanius:promise@1.03` in `.meteor/packages` 

That should fix at least one of your errors, let me know how it goes after.

**Comment by tehfailsafe** [comment]
Thanks for the info, but even without adding the done method at all I still can't get the promises to work. I think I simply don't understand where/how to create the correct functions.

In your example in the readme, you create a `createCustomer` function that returns a promise to `createCustomer`. Then you call that function with `Meteor.promise("createCustomer")`? Which createCustomer function is it referring to? It looks like `Meteor.promise("function")` should look for a `Meteor.methods` function, but you created a generic one with the same name then promised it? 

Following the stripe example, I have two meteor methods `stripeCreateCustomer` and `stripeCreateSubscription` which uses the fibers/future stuff. How should I lay out my `Meteor.promise` to first call `stripeCreateCustomer` and then `stripeCreateSubsription`?

**Comment by chicagogrooves** [comment]
I completely updated the README, correcting errors and simplifying.

Particularly I went to the style where the functions inside of `then` are unnamed. Declaring functions to use as promise steps, prior to using them is an optional, advanced thing. I see the confusion it was causing, as they were named similar to the ones on the server, yet doing slightly different things.

Also, in your case I want to point out that you don't typically want to use Promises on the server, in the `Meteor.methods` call, you use them only in the browser to sequence and error-handle the `Meteor.call` that you make.

Does that clear it up now ?

**Comment by tehfailsafe** [comment]
I ended up dumping most of the meteor chef's code. It was simply too confusing for me to follow, he was calling a server method that then called two more server methods, which used futures. Combining all the futures + promises + callbacks was too confusing for my simple brain.

Also the stripe API changed and you can now create the customer and subscription at the same time.

I ended up with this, seems like I got it right based on your last update!

client/userProfile.js
``` javascript

createSubscription(){
    Stripe.setPublishableKey("pk_test_qM3GFDAvf5FM5N6gh4sJtrqR")

    # update to real content, just using placeholder CC number for now
    Stripe.card.createToken({
      number: "4242424242424242",
      cvc: "123",
      exp_month: "12",
      exp_year: "17",
    }, (status, response) => {
      stripeToken = response.id;

      Meteor.promise("createSubscription", stripeToken, this.user)
        .then( (customer) => {
          return Meteor.promise("updateUser", customer, this.user)
        })
        .done(function(){
          console.log("done?");
        })
    });
  },

**Comment by chicagogrooves** [comment]
Nice. And ES6 too :)

**Comment by tehfailsafe** [comment]
Actually, I am now getting a new error: `Uncaught TypeError: undefined is not a function` which points to my catch function:

``` javascript
Meteor.promise("createSubscription", stripeToken, this.props.user)
        .then(function(customer){
          return Meteor.promise("updateUser", customer, self.props.user)
        })
        .then(function(){
          console.log("done i think");
        })
        .catch(function(error) {
          console.log("error! : ", error);
        })
    });
```


Do you see anything glaringly obvious? I am trying to trigger the error state by signing up a customer for a plan that doesn't exist, but instead it goes through and throws that error.

**Comment by chicagogrooves** [comment]
I don't see anything - if you look at the tests: https://github.com/chicagogrooves/deanius-meteor-promise/blob/master/tests/chaining-tests.next.js , they should show some passing examples with `catch`.

You can run them locally by cloning this repo, and doing `meteor test-packages ./` then browsing to the address it shows.. It might be easier to try some examples outside of the stripe environment, just a thought.

**Comment by chicagogrooves** [comment]
If you think you found a bug, reopen this and let's look at a PR with a failing test case (it's really simple).
